const data = {
  products: [
    {
      _id: '1',
      name: 'D.S. Luminescent Watercolors',
      category: 'Paint',
      image: '/images/p1.jpg',
      price: 25,
      countInStock: 12,
      brand: 'Daniel Smith',
      rating: 3.2,
      numReviews: 12,
      description: 'DANIEL SMITH Luminescent (Shimmering) Watercolors are wonderful for painting the special visual effects found in nature.',
    },
    {
      _id: '2',
      name: 'Faber-Castell Paint Brushes',
      category: 'Brushes',
      image: '/images/p2.jpg',
      price: 5,
      countInStock: 20,
      brand: 'Faber-Castell',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Arteza Streched Canvas',
      category: 'Canvas',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 0,
      brand: 'Arteza',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Leonid Afremov Painting',
      category: 'Paintings',
      image: '/images/p4.jpg',
      price: 200,
      countInStock: 15,
      brand: 'Leonid Afremov',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Bentonite Clay',
      category: 'Sculpture',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Blants',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Stabilo Fineliners',
      category: 'Pens',
      image: '/images/p6.jpg',
      price: 25,
      countInStock: 12,
      brand: 'Stabilo',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;